<?php
/**
 * OntoWiki rdf upload import import template
 */
$translate = OntoWiki::getInstance()->translate;
$urlBase = OntoWiki::getInstance()->getUrlBase();
//$default_licensee = OntoWiki::getInstance()->getConfig()->readOnly();
?>
<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/counterimporter/templates/counterimporter/js/typeahead.bundle.js')?>"></script>
<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/counterimporter/templates/counterimporter/js/handlebars.js')?>"></script>
<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/counterimporter/templates/counterimporter/js/search.js')?>"></script>
<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/themes/silverblue/scripts/libraries/jquery-ui.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo ($urlBase . 'extensions/counterimporter/templates/counterimporter/css/counter.css')?>">
<link rel="stylesheet" type="text/css" href="<?php echo ($urlBase . 'extensions/counterimporter/templates/counterimporter/css/hint.min.css')?>">
<fieldset class="activeForm" id="importdata">
    <legend><?php echo $this->_($translate->translate('Upload a Counter XML file')) ?></legend>
    <div class="width49 float margin">
        <div>
            <p class="messagebox info">
                <?php echo $this->_($translate->translate(
                    'Please select a UTF-8 encoded COUNTER XML File to import. (Note: Only COUNTER Version 4 supported)'
                ))?>
            </p>
        </div>
        <div>
            <label for="file-input">
                <?php echo sprintf(
                    $this->_('File (max. %1$sB)'),
                    preg_replace('/([kMG])/', ' $1', ini_get('upload_max_filesize'))
                ) ?>
            </label>
            <input type="file" id="file-input" name="source" />
            <br class="clearall"/>
        </div>
        <div>
            <p class="messagebox info">
                <?php echo $this->_($translate->translate(
                    'Please select the organization that is the licensor of the statistical data that will be retrieved.'
                ))?>
            </p>
        </div>
        <div class="sushi-field">
            <input  id="licensor-organization-input" class="typeahead width67" type="text" value="" name="licensor-organization-input"/>
        </div>
        <div>
            <p class="messagebox info">
                    Please select the organization that is the licensee of the statistical data that will be retrieved.
            </p>
        </div>
        <div class="sushi-field">
            <input  id="licensee-organization-input" class="typeahead width67" type="text" value="<?php echo $this->default_licensee ?>" name="licensee-organization-input"/>
        </div>
    </div>
</fieldset>
