<?php
/**
 * OntoWiki rdf upload import import template
 */
$translate = OntoWiki::getInstance()->translate;
?>
<fieldset class="activeForm" id="importdata">
    <legend><?php echo $this->_($translate->translate('Chose your SUSHI vendor')) ?></legend>
    <div class="width69 float margin">
        <div>
            <p class="messagebox info"><?php echo $translate->translate(
                    'Please select the SUSHI data you want to use for COUNTER import.'
                ) ?></p>
        </div>
        <div class="width69 float margin">
            <input id="sushi-input" class="typeahead" type="text" value="" name="sushi-input"/>
        </div>
        <p class="messagebox info"><?php echo $translate->translate(
                'Please specify the date range.'
            ) ?></p>
        <div>
            <label class="text" for="datepicker1"><?php echo $translate->translate(
                    'Start date'
            ) ?></label>
            <input id="datepicker1" class="ui-datepicker text" type="date" value="" name="from" />
        </div>
        <div>
            <label class="text" for="datepicker2"><?php echo $translate->translate(
                'End date'
            ) ?></label>
            <input id="datepicker2" class="ui-datepicker text" type="date" value="" name="to" />
        </div>
    </div>
</fieldset>
